# Categorical Data Analysis                                           :categ:
:PROPERTIES:
:tangle: R/15-categ.R
:CUSTOM_ID: cha-Categorical-Data-Analysis
:END:

```{r, echo=FALSE, eval=FALSE}
#    IPSUR: Introduction to Probability and Statistics Using R
#    Copyright (C) 2014  G. Jay Kerns
#
#    Chapter: Categorical Data Analysis
#
#    This file is part of IPSUR.
#
#    IPSUR is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    IPSUR is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with IPSUR.  If not, see <http://www.gnu.org/licenses/>.
```

This chapter is still under substantial revision. At any time you can
preview any released drafts with the development version of the
=IPSUR= package which is available from \(\mathsf{R}\)-Forge:

```{r, echo=TRUE, eval=FALSE}
install.packages("IPSUR", repos="http://R-Forge.R-project.org")
library("IPSUR")
read(IPSUR)
```

